# Generated by Django 5.0.1 on 2024-03-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='discord_link',
            field=models.URLField(blank=True),
        ),
    ]
